# Generated by Django 3.1.7 on 2021-03-16 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('biography', models.TextField(verbose_name='Biography')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Age')),
                ('photo', models.ImageField(upload_to='actors/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Actor and Director',
                'verbose_name_plural': 'Actors and Directors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Category')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Film_Category',
                'verbose_name_plural': 'Films_Categories',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Film')),
                ('poster', models.ImageField(upload_to='films/', verbose_name='Poster')),
                ('plot', models.TextField(verbose_name='Film_plot')),
                ('release_year', models.SmallIntegerField(default=2020, verbose_name='Release Year')),
                ('running_time', models.SmallIntegerField(default=100, verbose_name='Running time')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('slug', models.SlugField(unique=True)),
                ('actors', models.ManyToManyField(related_name='film_actor', to='films.Actors', verbose_name='Film actors')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='films.category', verbose_name='Category')),
                ('directors', models.ManyToManyField(related_name='film_director', to='films.Actors', verbose_name='Film directors')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Genres')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='IP')),
                ('rating', models.SmallIntegerField(verbose_name='rating')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film', verbose_name='Film')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(to='films.Genre', verbose_name='genre'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
                ('comment', models.TextField(max_length=2000, verbose_name='review')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film', verbose_name='Film')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
