# Generated by Django 3.1.7 on 2021-06-11 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='date_added',
            field=models.DateField(default=datetime.date.today, verbose_name='Movie added'),
        ),
    ]
