# Generated by Django 3.1.7 on 2021-06-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='editor_choice',
            field=models.BooleanField(default=False),
        ),
    ]
