# Generated by Django 3.1.7 on 2021-06-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_film_editor_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
