# Generated by Django 3.1.7 on 2021-06-30 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_film_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Photo')),
                ('stills', models.ImageField(upload_to='stills/', verbose_name='photo')),
                ('films', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film', verbose_name='film')),
            ],
            options={
                'verbose_name': 'still',
                'verbose_name_plural': 'stills',
            },
        ),
    ]
