# Generated by Django 3.1.7 on 2021-07-09 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_comment_posted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parent', to='films.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=2000, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='stills',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
    ]
