# Generated by Django 3.1.7 on 2021-09-25 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0016_auto_20210913_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dislike',
            new_name='dislikes',
        ),
    ]
