# Generated by Django 3.1.7 on 2021-10-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0017_auto_20210925_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='video',
            field=models.FileField(null=True, upload_to='video/', verbose_name='video'),
        ),
    ]
