# Generated by Django 3.1.7 on 2021-10-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0018_film_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='video',
            field=models.FileField(default='https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-576p.mp4', upload_to='video/', verbose_name='video'),
        ),
    ]
