# Generated by Django 3.1.7 on 2022-03-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='avatar/user.svg', upload_to='avatar/', verbose_name='Avatar'),
        ),
    ]
